### ISSUE TITLE
Cannot install gem. 

### ISSUE THREAD

**Issue by rsedighi** [kennon/litmos-client#2]
'gem install litmos-client' gives the following error. Do you have any insight as to why this might be happening? 

```
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between litmos-client and litmos-client
```

**Comment by kennon** [comment]
Hi, I tweaked some dependencies so it should be installable now. However, I haven't even looked at the Litmos API in ~4 years, so no idea if this actually even still works :-)
