### ISSUE TITLE
undefined method blank? for  RestClient::Response / String

### ISSUE THREAD

**Issue by pikitgb** [kennon/litmos-client#3]
Hi Kennon Ballou, thanks for the litmos-client.

I'm having an issue with the blank? method for the String class and RestClient::Response and idk if that is normal my current ruby version is kind of old (ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-darwin10.8.0]) and not sure if is that. Just leaving this here in case can help somebody else.

require 'rest_client'
require 'litmos-client'

if (!RestClient::Response.new.methods.include?(:blank?))
    class RestClient::Response
      def blank?
          self.nil?
      end
    end
end

if (!String.new.methods.include?(:blank?))
    class String
      def blank?
        self.nil?
      end
    end
end

litmos = LitmosClient::API.new('YOUR-API-KEY', 'URL')
 
Regards.

**Comment by kennon** [comment]
@pikitgb ```.blank?``` is a Rails extension - if you are using this in vanilla Ruby then it won't be there. I'm not really maintaining this gem any more, but if you would like to submit a PR that replaces ```.blank?```, I'd be happy to merge it in.
